#! /bin/sh

feh --bg-fill ~/Downloads/wallpaper.jpg &
picom --experimental-backends &
~/.config/polybar/launch.sh &
redshift -PO 3600 -b 0.85 &
pgrep -x sxhkd -m -1 > /dev/null || sxhkd -m -1 &

bspc monitor DisplayPort-1 -d I II III IV V VI
bspc monitor DisplayPort-2 -d VII VIII IX X

bspc config border_width	2
bspc config window_gap		12

bspc config split_ratio          0.52
bspc config borderless_monocle   false
bspc config gapless_monocle     false 

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off