#! /bin/sh
#Cambiar de monitores
#xrandr --output eDP-1 --off
#xrandr --output eDP-1 --left-of HDMI-1
pgrep -x sxhkd > /dev/null || sxhkd &
picom --experimental-backends &
redshift -PO 4700 -b 1 &
#Esto es para la mona china
feh --bg-fill ~/Descargas/mo.jpeg &
bash ~/.config/polybar/launch.sh --forest &
#$HOME/.config/polybar/launch.sh &

bspc monitor HDMI-1 -n monitor0 -d I II III IV 
bspc monitor eDP-1 -n monitor1 -d V VI VII VIII IX X
bspc monitor HDMI-0 -s DP-0

bspc config border_width         2
bspc config window_gap         	 5 
bspc config focused_border_color "#0ddb90"
bspc config normal_border_color "#4c566a"
bspc config focus_follows_pointer true
bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true 
bspc config focus_by_distance true
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Zathura state=tiled follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
